In [2]:
import re
import pandas as pd

import nltk
from nltk.tokenize import wordpunct_tokenize
from gensim.models.fasttext import FastText


from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('../data/preprocess_train.csv')
df

name_1  \
0                                iko industries ltd.   
1                            apcotex industries ltd.   
2                  rishichem distributors pvt., ltd.   
3                            powermax rubber factory   
4                                          tress a/s   
...                                              ...   
497814                              bit-mat products   
497815                         bnd trading co., ltd.   
497816  xeikon industrial co., ltd. of dongguan city   
497817            shanghai kechuan trading co., ltd.   
497818                        dih wei industries co.   

                                                   name_2  is_duplicate  
0                    enormous industrial trade pvt., ltd.             0  
1                     technocraft industries (india) ltd.             0  
2                                                     dsa             0  
3                                                 co. one             0  
4                        longyou industries park zhejiang             0  
...                                                   ...           ...  
497814               the goodyear tire and rubber company             0  
497815  zhong shan yue liang economy& trade imp. & exp...             0  
497816        yi cheng trading co., ltd. of dongguan city             0  
497817                       shanghai m&g stationery inc.             0  
497818                    burlington industries corporate             0  

[497819 rows x 3 columns]

In [4]:
df['name_1'] = df['name_1'].apply(lambda x: re.sub(r'[^\w\s]+|[\d]+', r'', x))
df['name_1'] = df['name_1'].apply(lambda x: re.sub(r'[.,"\'-?:!;&]', r'', x))
df['name_2'] = df['name_2'].apply(lambda x: re.sub(r'[^\w\s]+|[\d]+', r'', x))
df['name_2'] = df['name_2'].apply(lambda x: re.sub(r'[.,"\'-?:!;&]', r'', x))

df['name_1'] = df['name_1'].apply(lambda x: x.replace(' ', '') if len(x) <= 6 else x)
df['name_2'] = df['name_2'].apply(lambda x: x.replace(' ', '') if len(x) <= 6 else x) 

In [6]:
all_sentens = list(set(df['name_1']) & set(df['name_2']))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [7]:
from nltk.tokenize import wordpunct_tokenize
word_tokenized_corpus = [wordpunct_tokenize(sent) for sent in list(set(X_train['name_1']) & set(X_train['name_2']))]

NameError: name 'X_train' is not defined

In [ ]:
X_train

name_1  \
133032  indus pencil industries private ltd   
162907            mac resolute services ltd   
19406                          evonik india   
333205        dongguan haocheng toys co ltd   
460977                        marav usa llc   
...                                     ...   
13501                            comagro sa   
130642        coto technology s de rl de cv   
372089                       divetis mexico   
408700                  al chem corporation   
289128         alp nishikawa co private ltd   

                                              name_2  
133032                 suja shoei industries pvt ltd  
162907                                     uma solar  
19406   fischer building materials india private ltd  
333205     dongguan mayor bean shoes material co ltd  
460977                                  ht cargo usa  
...                                              ...  
13501             plasticos agricolas y geomembranas  
130642                     adhesives technology corp  
372089           altex products mexico s de rl de cv  
408700  irinotecan european chemical shanghai co ltd  
289128                                     captivate  

[199127 rows x 2 columns]

In [ ]:
word_tokenized_corpus

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
for i in df.index:
  print(i)
  break

0


In [ ]:
!python --version


Python 3.7.15


In [ ]:
deposit = 100000
rate = .06
deposit_term = 5
while (deposit_term != 0):
    deposit *= (1 + rate)
    deposit_term -= 1
deposit = round(deposit, 2)
print(deposit)

133822.56


In [ ]:

deposit = 100000 # Переменной deposit присваивается значение 100000
rate = 0.06 # Переменной rate присваивается значение 0.06
deposit_term = 5 # Переменной deposit_term присваивается значение 5  
  
for i in range(0,deposit_term): # Цикл, в котором количество итераций соответствует deposit_term
    deposit = deposit + deposit * rate # Начисленные за год проценты добавляются к сумме вклада
deposit = round(deposit,2) # Округление результата до копеек
print(deposit)

133822.56


In [ ]:
def solve(a,b):
    if (b == 0 and a != 0):
        return "Any"
    elif (b != 0 and a == 0):
        return "Error"
    else:
        return (b/a)

In [ ]:
solve(10, 0)

'Any'

In [ ]:
def make_predict(ft_model, df):
  preds = []
  for i in df.index:
    proba = ft_model.wv.similarity(df['name_1'][i], df['name_2'][i])
    preds.append(proba)
    # if proba >= trash:
    #   preds.append(1)
    # else:
    #   preds.append(0)
  return preds

  

In [ ]:
def find_min_trash(ft_model, df):
  trash = 12
  for i,j in enumerate(df[df['is_duplicate'] == 1]['name_1']):
    proba = ft_model.wv.similarity(df['name_1'][i], df['name_2'][i])
  if proba < trash:
    trash = proba
  return trash

In [ ]:
def learning(model):
  embedding_size = 10
  window_size = 7
  min_word = 1
  down_sampling = 1e-2
  max_recall = 0
  for i in range(1, 11):
    model.train(word_tokenized_corpus, total_examples=model.corpus_count, epochs=i)
    if (max_recall > recall_score(df['is_duplicate'], make_predict(model,df, find_min_trash(model, df)))):
      print(recall_score(df['is_duplicate'], make_predict(model,df, find_min_trash(model, df))), i)
      max_reall = recall_score(df['is_duplicate'], make_predict(model,df, find_min_trash(model, df)))
      model.save('/content/drive/MyDrive/best_model.fasttext')
    print()
    
    
    

In [ ]:
learning()

1
2
3
4
5
6
7
8
9
10


In [ ]:
model = FastText(size=100, window=5, min_count=1, workers=4, sg=1)
model.build_vocab(word_tokenized_corpus)

In [ ]:
model.iter

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  """Entry point for launching an IPython kernel.


5

In [ ]:
model.train(word_tokenized_corpus, total_examples=model.corpus_count, epochs=model.iter)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  """Entry point for launching an IPython kernel.
Exception in thread Thread-278:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gensim/models/base_any2vec.py", line 211, in _worker_loop
    tally, raw_tally = self._do_train_job(data_iterable, job_parameters, thread_private_mem)
  File "/usr/local/lib/python3.7/dist-packages/gensim/models/fasttext.py", line 593, in _do_train_job
    tally += train_batch_sg(self, sentences, alpha, work, neu1)
  File "gensim/models/fasttext_inner.pyx", line 322, in gensim.models.fasttext_inner.train_batch_sg
TypeError: 'NoneType' object is not subscriptable

Exc

KeyboardInterrupt: ignored

In [ ]:
import numpy as np
from sklearn.metrics import precision_recall_curve
precision, recall, thresholds = precision_recall_curve(y_val, make_predict(model, X_val))
np.where(precision > 0.80)

(array([123992, 123993, 123994, 123995]),)

In [ ]:
precision, recall, thresholds

(array([0.00738268, 0.007376  , 0.00737605, ..., 0.82608696, 1.        ,
        1.        ]),
 array([1.        , 0.99908842, 0.99908842, ..., 0.01731996, 0.00182315,
        0.        ]),
 array([0.8575537 , 0.8576203 , 0.8577053 , ..., 0.99999994, 1.        ,
        1.0000001 ], dtype=float32))

In [ ]:
def make_predict_class(ft_model, df):
  preds = []
  for i in df.index:
    proba = ft_model.wv.similarity(df['name_1'][i], df['name_2'][i])
    if proba >= 0.99999990:
      preds.append(1)
    else:
      preds.append(0)
  return preds

In [ ]:
preds = make_predict_class(model,X_val)

In [ ]:
recall_score(y_val, preds)

0.020966271649954422

In [ ]:
precision_score(y_val, preds)

0.8214285714285714

In [ ]:
f1_score(y_val, preds)

0.04088888888888889

In [ ]:
thresholds[123992]

0.99999994

In [ ]:
trash = 12
for i,j in enumerate(df[df['is_duplicate']==1]['name_1']):
  # proba = ft_model.wv.similarity(df['name_1'][i], df['name_2'][i])
  proba = model.wv.similarity(df['name_1'][i], df['name_2'][i])
  print(df['name_1'][i], df['name_2'][i],proba)
  if proba < trash:
    trash = proba
    print(trash)

# Классификатор

In [ ]:
!pip install fasttext==0.9.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 68 kB 6.5 MB/s 
  Using cached pybind11-2.10.0-py3-none-any.whl (213 kB)
  Created wheel for fasttext: filename=fasttext-0.9.2-cp37-cp37m-linux_x86_64.whl size=3164775 sha256=4229bdc88d939338411f9b0a04b71f558797b26225a8a52651b8dea9ba29a297
  Stored in directory: /root/.cache/pip/wheels/4e/ca/bf/b020d2be95f7641801a6597a29c8f4f19e38f9c02a345bab9b
Successfully built fasttext


In [ ]:
import fasttext

Необязательно запускать

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/preprocess_train.csv')

df['name_1'] = df['name_1'].apply(lambda x: re.sub(r'[^\w\s]+|[\d]+', r'', x))
df['name_1'] = df['name_1'].apply(lambda x: re.sub(r'[.,"\'-?:!;&]', r'', x))
df['name_2'] = df['name_2'].apply(lambda x: re.sub(r'[^\w\s]+|[\d]+', r'', x))
df['name_2'] = df['name_2'].apply(lambda x: re.sub(r'[.,"\'-?:!;&]', r'', x))
df['name_1'] = df['name_1'].apply(lambda x: x.replace(' ', '') if len(x) <= 6 else x) 
df['name_2'] = df['name_2'].apply(lambda x: x.replace(' ', '') if len(x) <= 6 else x)

In [ ]:
df['common'] = df['name_1'] + " /SEP/  " +  df['name_2'] 

In [ ]:
df['is_duplicate_str'] = df['is_duplicate'].replace({0 : '__label__NEGATIVE', 1: '__label__POSITIVE'})

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.common, df.is_duplicate_str, test_size=0.2, stratify=df.is_duplicate_str)

In [ ]:
train_df = pd.DataFrame({'common': X_train, 'is_duplicate_str' :y_train})[:398256 - 1]
train_df

common   is_duplicate_str
321747            excel polymer industries /SEP/  stp ltd  __label__NEGATIVE
915     qingdao xinhongtai logistics co ltd /SEP/  qin...  __label__NEGATIVE
168449  dependable distribution /SEP/  volume distribu...  __label__NEGATIVE
227918      pl /SEP/  ik plastic compound mexico sa de cv  __label__NEGATIVE
173407  synthomer llc peachtree lenox bl bonded logist...  __label__NEGATIVE
...                                                   ...                ...
78031             llc ikea torg  /SEP/  a s international  __label__NEGATIVE
90208     industries commodities inc /SEP/  kl industries  __label__NEGATIVE
371069  especialidades quimicas de colombia  compania ...  __label__NEGATIVE
388658      lagan bitumen ltd /SEP/  orlen asfalt sp z oo  __label__NEGATIVE
303064             ttc logistics inc /SEP/  logistics ltd  __label__NEGATIVE

[398255 rows x 2 columns]

Обязательно запускать 


In [ ]:
train_df.to_csv(r'/content/drive/MyDrive/company.train', index=False, sep=' ', header=False,  escapechar=" ")

In [ ]:
ft_model = \
 fasttext.train_supervised(input="/content/drive/MyDrive/company.train", epoch=10, lr=.01, wordNgrams=2, minn=2 ,maxn=5)

In [ ]:
ft_model.save_model('/content/drive/MyDrive/company_model.bin')

In [ ]:
preds_text = X_test.apply(lambda x: ft_model.predict(x, threshold=0.5)[0][0])

In [ ]:
preds_num = []
for i in preds_text:

  if i == '__label__NEGATIVE':
    preds_num.append(0)
  else:
    preds_num.append(1)

In [ ]:
y_test = y_test.replace({'__label__NEGATIVE' : 0, '__label__POSITIVE' : 1})

In [ ]:
print(recall_score(y_test, preds_num))
print(precision_score(y_test, preds_num))
print(f1_score(y_test, preds_num, average='macro'))

0.5286885245901639
0.8795454545454545
0.8291995042577462
